# Generated by Django 3.1.3 on 2020-11-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('done', models.CharField(choices=[('doing', 'DOING'), ('done', 'DONE')], max_length=5)),
                ('createad_at', models.DateField(auto_now_add=True)),
                ('updatead_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
